backend:
  name: github
  repo: Hyun-git/Hyun-git.github.io
  branch: main
  base_url: https://decap-cms-oauth.vercel.app/

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "about.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "index"
        label: "Home Page"
        file: "index.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "data"
    label: "Data"
    files:
      - name: "menu"
        label: "Menu"
        file: "_data/menu.yml"
        fields:
          - name: "entries"
            label: "Menu Entries"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - name: "entries"
                label: "Sub Entries"
                widget: "list"
                required: false
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "URL", name: "url", widget: "string", required: false }
              - name: "post_list"
                label: "Post List Settings"
                widget: "object"
                required: false
                fields:
                  - { label: "Show More", name: "show_more", widget: "boolean" }
                  - { label: "Show More Text", name: "show_more_text", widget: "string" }
                  - { label: "Show More URL", name: "show_more_url", widget: "string" }
